language: ruby
rvm:
- 2.3.0
script:
- rspec
deploy:
  provider: rubygems
  api_key:
    secure: dkyGCTisaOFW8WAtd8w7q+Cb2W4VZUzt+wCjoLXByxFp+hecFfuL8ocn7boObWLzQIz1a/+ULM7ArYDAH1UaHJU/tIQ+IXuzMoir7Uu5mVWaEPKZvYJMcrXE6SlCmjoCII2aHA/aLFl6XNkC7SexJvMLilH13D09qsPbktRdas8KTlT/bEorNTFq+1FZxxP/8LKMPqT/PyrrCWUUhrsG5+k8SqXVvL2ooSftn/ROAW38ETaU+mgyKsErWZhnhF1Gioft/VlSXSrmKeXNn4utFMkEI/dl6lmDHmDtr+I11IDn+hsvU/iYNly48IQWVlDu8mZ+TeColG8G/h3MjlWd4SUqaLIyDnNKgHU+/0og7i/UnKl/fu/qYN3kXPxJVWuH0g200llAwVvKyw1zy4Ddw/BGPAp7Sj8Wbcag3fGni7JkVXsZK0TzNNS4oCQUrwsYQNIGCnPZem0W9fVWwVJQSY8vvnw1owcS/Glzk96QlRnWfSO8mZ43so2TdglEiPGAAUZDSrQY+r/kvf+Fv5DGVU3cvPx7GY8MmEliATL3xL9wnlWVMoTzzgp9dhM8LMR37I/GZd5nwHqr0KXBgFDqL1puHtcjHT5lhRY9K+QLhFBw/A/gJuTA+5aLQnfmd8q0JMT//kHNdzQLl89T+ZE6FIfTKqiFPdhETGaIwnqXISo=
  gem: squcumber-postgres
  on:
    tags: true
    repo: moertel/sQucumber-postgres
